services:
  - type: web
    name: quizly-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: client/dist
    envVars:
      - key: VITE_API_URL
        value: https://quiz-1-f2c7.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  - type: web
    name: quiz-platform-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
