// Judge0 CE language IDs. The compiler service can override individual IDs.
export const compilerLanguages = [
  ['c', 'C', 50, '#include <stdio.h>\nint main(void) {\n    printf("Hello, C!\\n");\n    return 0;\n}'],
  ['cpp', 'C++', 54, '#include <iostream>\nint main() {\n    std::cout << "Hello, C++!" << std::endl;\n    return 0;\n}'],
  ['java', 'Java', 62, 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, Java!");\n    }\n}'],
  ['nodejs', 'Node.js', 63, 'console.log("Hello, Node.js!");'],
  ['bash', 'Bash', 46, '#!/usr/bin/env bash\necho "Hello, Bash!"'],
  ['csharp', 'C#', 51, 'using System;\nclass Program {\n    static void Main() { Console.WriteLine("Hello, C#!"); }\n}'],
  ['typescript', 'TypeScript', 74, 'const message: string = "Hello, TypeScript!";\nconsole.log(message);'],
  ['go', 'Go', 60, 'package main\nimport "fmt"\nfunc main() { fmt.Println("Hello, Go!") }'],
  ['rust', 'Rust', 73, 'fn main() { println!("Hello, Rust!"); }'],
  ['kotlin', 'Kotlin', 78, 'fun main() { println("Hello, Kotlin!") }'],
  ['swift', 'Swift', 83, 'print("Hello, Swift!")'],
  ['php', 'PHP', 68, '<?php\necho "Hello, PHP!\\n";'],
  ['ruby', 'Ruby', 72, 'puts "Hello, Ruby!"'],
  ['r', 'R', 80, 'cat("Hello, R!\\n")'],
  ['dart', 'Dart', 90, 'void main() { print("Hello, Dart!"); }'],
  ['scala', 'Scala', 81, 'object Main { def main(args: Array[String]): Unit = println("Hello, Scala!") }'],
  ['perl', 'Perl', 85, 'print "Hello, Perl!\\n";'],
  ['lua', 'Lua', 64, 'print("Hello, Lua!")'],
  ['haskell', 'Haskell', 61, 'main = putStrLn "Hello, Haskell!"'],
  ['elixir', 'Elixir', 57, 'IO.puts("Hello, Elixir!")'],
  ['erlang', 'Erlang', 58, '-module(main).\n-export([main/0]).\nmain() -> io:format("Hello, Erlang!~n").'],
  ['clojure', 'Clojure', 86, '(println "Hello, Clojure!")'],
  ['groovy', 'Groovy', 88, 'println "Hello, Groovy!"'],
  ['fortran', 'Fortran', 59, 'program main\n  print *, "Hello, Fortran!"\nend program main'],
  ['pascal', 'Pascal', 67, 'program Main;\nbegin\n  writeln(\'Hello, Pascal!\');\nend.'],
  ['ocaml', 'OCaml', 65, 'print_endline "Hello, OCaml!";;'],
  ['octave', 'Octave', 66, 'disp("Hello, Octave!");'],
  ['d', 'D', 56, 'import std.stdio;\nvoid main() { writeln("Hello, D!"); }'],
  ['common-lisp', 'Common Lisp', 55, '(format t "Hello, Lisp!~%")'],
  ['prolog', 'Prolog', 69, ':- initialization(main).\nmain :- write(\'Hello, Prolog!\'), nl, halt.'],
  ['fsharp', 'F#', 87, 'printfn "Hello, F#!"'],
  ['vbnet', 'Visual Basic .NET', 84, 'Module Main\n    Sub Main()\n        System.Console.WriteLine("Hello, Visual Basic!")\n    End Sub\nEnd Module'],
  ['basic', 'Basic', 47, 'PRINT "Hello, Basic!"'],
  ['cobol', 'COBOL', 77, '       IDENTIFICATION DIVISION.\n       PROGRAM-ID. MAIN.\n       PROCEDURE DIVISION.\n           DISPLAY "Hello, COBOL!".\n           STOP RUN.'],
  ['objective-c', 'Objective-C', 79, '#include <stdio.h>\nint main(void) { printf("Hello, Objective-C!\\n"); return 0; }'],
  ['assembly', 'Assembly', 45, 'section .data\n    msg db "Hello, Assembly!", 10\n    len equ $ - msg\nsection .text\n    global _start\n_start:\n    mov eax, 4\n    mov ebx, 1\n    mov ecx, msg\n    mov edx, len\n    int 0x80\n    mov eax, 1\n    xor ebx, ebx\n    int 0x80'],
]
export const compilerLanguageIds = Object.fromEntries(compilerLanguages.map(([runtime, , id]) => [runtime, id]))
