const question = (text, options, correctAnswer, explanation) => ({ text, options, correctAnswer, explanation })
const topic = (name, slug, easy, medium, hard, children = []) => ({
  name,
  slug,
  icon: 'book',
  questions: [
    { difficulty: 'Easy', ...easy },
    { difficulty: 'Medium', ...medium },
    { difficulty: 'Hard', ...hard },
  ],
  children,
})
const legacy = (name, slug, icon, easy, medium, hard) => ({
  ...topic(name, slug, easy, medium, hard),
  icon,
  legacy: true,
})

export const subjectGroups = [
  {
    name: 'Science', slug: 'science', description: 'Explore the natural world, from tiny cells to distant stars.', icon: 'atom', color: '#4b9b8b', children: [
      topic('Physics', 'physics',
        question('Which unit measures force?', ['Joule', 'Newton', 'Watt', 'Pascal'], 1, 'The newton is the SI unit of force.'),
        question('In a series circuit, what is the same through every component?', ['Voltage', 'Resistance', 'Current', 'Power'], 2, 'A series circuit has one path, so the current is the same through each component.'),
        question('If a planet gains mass while keeping the same radius, what happens to its escape velocity?', ['It increases', 'It decreases', 'It stays the same', 'It becomes zero'], 0, 'Escape velocity is proportional to the square root of mass divided by radius.'),
      ),
      topic('Chemistry', 'chemistry',
        question('A solution with a pH of 3 is best described as:', ['Acidic', 'Neutral', 'Basic', 'Saturated'], 0, 'Values below 7 are acidic on the pH scale.'),
        question('What happens to electrons in a covalent bond?', ['They are shared', 'They are destroyed', 'They become neutrons', 'They move only to metals'], 0, 'Covalent bonds form when atoms share electron pairs.'),
        question('Why can a buffer resist a sudden change in pH?', ['It contains a weak acid and its conjugate base', 'It contains only pure water', 'It removes every ion from solution', 'It always has a pH of 7'], 0, 'A conjugate acid-base pair can absorb added acid or base.'),
      ),
      topic('Biology', 'biology',
        question('Which cell structure releases most usable energy from food?', ['Mitochondrion', 'Ribosome', 'Cell wall', 'Golgi apparatus'], 0, 'Mitochondria carry out most cellular aerobic respiration.'),
        question('What is the usual result of meiosis?', ['Two identical diploid cells', 'Four haploid cells', 'One unchanged cell', 'Four diploid cells'], 1, 'Meiosis produces four cells with half the parent cell chromosome number.'),
        question('Natural selection changes a population most directly when:', ['Inherited variations affect reproductive success', 'Individuals choose new genes', 'Every mutation is beneficial', 'All members reproduce equally'], 0, 'Heritable traits linked to reproductive success become more common over generations.'),
      ),
      topic('Astronomy', 'astronomy',
        question('Which planet is commonly called the Red Planet?', ['Venus', 'Mars', 'Jupiter', 'Mercury'], 1, 'Iron-rich dust gives Mars its reddish appearance.'),
        question('A light-year is a measure of:', ['Time', 'Brightness', 'Distance', 'Mass'], 2, 'A light-year is the distance light travels in one year.'),
        question('A star whose spectral lines are shifted toward longer wavelengths is generally:', ['Moving away from the observer', 'Moving toward the observer', 'Not emitting light', 'Closer than every blue-shifted star'], 0, 'Redshift indicates recession along the line of sight.'),
      ),
      topic('Environmental Science', 'environmental-science',
        question('Which gas do plants absorb during photosynthesis?', ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Helium'], 1, 'Plants use carbon dioxide as a carbon source during photosynthesis.'),
        question('Which resource is renewable when managed sustainably?', ['Coal', 'Sunlight', 'Natural gas', 'Uranium ore'], 1, 'Sunlight is replenished continuously on human timescales.'),
        question('Excess nitrogen and phosphorus entering a lake can cause:', ['Eutrophication and oxygen depletion', 'Lower water temperature only', 'Permanent sterilization of all soil', 'A reduction in algal growth'], 0, 'Nutrient enrichment can trigger algal blooms whose decay consumes dissolved oxygen.'),
      ),
    ],
  },
  {
    name: 'Technology', slug: 'technology', description: 'Understand the tools and systems shaping the digital world.', icon: 'code-2', color: '#527f9c', children: [
      topic('Programming', 'programming',
        question('What is a variable commonly used for?', ['Storing a value for later use', 'Compressing a network cable', 'Rendering a web page by itself', 'Deleting source code'], 0, 'A variable gives a value a name that a program can use.'),
        question('Binary search requires the input collection to be:', ['Sorted', 'A linked list only', 'Encrypted', 'Exactly 100 items long'], 0, 'Binary search discards half the remaining search space at each step in sorted data.'),
        question('A race condition occurs when a result depends on:', ['The unpredictable timing of concurrent operations', 'The order of variable names', 'The color of the user interface', 'A compiler warning alone'], 0, 'Concurrent operations can interleave differently and produce different outcomes.'),
        [
          legacy('JavaScript', 'javascript', 'code-2',
            question('Which keyword declares a block-scoped binding that cannot be reassigned?', ['const', 'var', 'return', 'throw'], 0, 'A const binding is block-scoped and cannot be reassigned.'),
            question('What does Promise.all() do if one input promise rejects?', ['Rejects with that reason', 'Returns only the fulfilled values', 'Retries the rejected promise', 'Waits forever for all remaining promises'], 0, 'Promise.all rejects as soon as an input rejects.'),
            question('After the current JavaScript call stack clears, which queue is processed before the next task?', ['Microtask queue', 'Animation task queue only', 'Network task queue always', 'The stack is never cleared'], 0, 'Promise reactions run as microtasks before the next task is taken.'),
          ),
          legacy('Python', 'python', 'terminal',
            question('Which value represents “no value” in Python?', ['None', 'null', 'undefined', 'void'], 0, 'Python uses the singleton value None.'),
            question('What does [n * 2 for n in range(3)] produce?', ['[0, 2, 4]', '[2, 4, 6]', '[0, 1, 2]', '[3, 6, 9]'], 0, 'range(3) yields 0, 1, and 2, each multiplied by two.'),
            question('What is the average-case lookup complexity for a key in a well-distributed Python dictionary?', ['O(1)', 'O(log n)', 'O(n)', 'O(n log n)'], 0, 'Hash-table lookup is average-case constant time.'),
          ),
          topic('Node.js', 'node-js',
            question('Which built-in Node.js module provides file-system operations?', ['fs', 'pathing', 'document', 'browser'], 0, 'The fs module provides file-system APIs.'),
            question('What does npm primarily manage in a Node.js project?', ['Packages and scripts', 'Browser cookies', 'HTML elements', 'Database rows'], 0, 'npm installs packages and runs project scripts.'),
            question('Why should CPU-heavy work be moved off Node.js’s event loop?', ['It can block other callbacks from running', 'It disables garbage collection', 'It changes JavaScript syntax', 'It prevents all network requests from starting'], 0, 'Long synchronous CPU work blocks the event loop and delays I/O callbacks.'),
          ),
          topic('Java', 'java',
            question('Which keyword declares a class in Java?', ['class', 'struct', 'define', 'object'], 0, 'Java class declarations begin with the class keyword.'),
            question('What does method overloading allow in Java?', ['Methods with the same name but different parameter lists', 'Changing a method’s return type alone', 'Calling private methods from any class', 'Creating multiple main methods with identical signatures'], 0, 'Overloads share a name but differ in their parameter lists.'),
            question('Which Java type is designed for immutable sequences of values in modern Java?', ['List.of(...) result', 'ArrayList with unrestricted mutation', 'A raw Object array', 'StringBuilder'], 0, 'List.of creates an unmodifiable list.'),
          ),
          topic('Git & GitHub', 'git-github',
            question('Which Git command records staged changes in a new commit?', ['git commit', 'git clone', 'git fetch', 'git status'], 0, 'git commit creates a commit from the staged snapshot.'),
            question('What does git pull commonly do?', ['Fetches remote changes and integrates them into the current branch', 'Deletes every remote branch', 'Stages all local files', 'Creates a new repository'], 0, 'git pull fetches and integrates changes, typically by merge or rebase.'),
            question('A pull request is primarily used to:', ['Propose and review changes before merging them', 'Replace the local Git database', 'Encrypt a repository', 'Automatically resolve every merge conflict'], 0, 'Pull requests provide a review and collaboration workflow before integration.'),
          ),
        ],
      ),
      topic('Web Development', 'web-development',
        question('Which language primarily describes the structure of a web page?', ['HTML', 'SQL', 'Bash', 'C'], 0, 'HTML provides the semantic document structure.'),
        question('In the CSS box model, padding sits between:', ['Content and border', 'Border and margin', 'Margin and outline', 'The page and viewport'], 0, 'Padding surrounds content and is inside the border.'),
        question('What does a browser CORS check help a server control?', ['Which web origins may read cross-origin responses', 'How passwords are hashed', 'How images are compressed', 'Which database indexes exist'], 0, 'Cross-Origin Resource Sharing lets servers declare permitted origins.'),
        [
          legacy('React', 'react', 'atom',
            question('Which function creates a React component element?', ['createElement', 'makeNode', 'renderHTML', 'newComponent'], 0, 'React.createElement creates an element description.'),
            question('Why does React use a key when rendering a list?', ['To identify items across renders', 'To encrypt each item', 'To choose a CSS color', 'To prevent every state update'], 0, 'Keys help React match list items between renders.'),
            question('When should an effect clean-up function run?', ['Before the effect reruns and when the component unmounts', 'Only after every browser refresh', 'Before the first render', 'Only when a promise resolves'], 0, 'React runs cleanup before rerunning an effect and on unmount.'),
          ),
          legacy('HTML', 'html', 'panels-top-left',
            question('Which element represents the main content of a page?', ['<main>', '<aside>', '<footer>', '<small>'], 0, 'The main element identifies the document’s primary content.'),
            question('What should a label’s for attribute match?', ['The associated input id', 'The input name only', 'The form action URL', 'The page title'], 0, 'The for value associates the label with the control whose id matches.'),
            question('Which attribute gives an image a text alternative when it cannot be seen?', ['alt', 'title only', 'role', 'loading'], 0, 'The alt attribute provides an accessible text alternative for an image.'),
          ),
          legacy('CSS', 'css', 'paintbrush',
            question('Which CSS property changes an element’s text color?', ['color', 'font-style', 'background-size', 'opacity'], 0, 'The color property sets the foreground text color.'),
            question('In CSS Grid, which property defines the columns of a grid container?', ['grid-template-columns', 'column-count', 'flex-direction', 'grid-auto-flow'], 0, 'grid-template-columns defines explicit grid column tracks.'),
            question('Which selector targets an element only while it has keyboard focus visible?', [':focus-visible', ':hover', ':visited', '::selection'], 0, ':focus-visible styles focus when the browser determines it should be visibly indicated.'),
          ),
          topic('React.js', 'react-js',
            question('Which React hook adds state to a function component?', ['useState', 'useRoute', 'useClass', 'useMarkup'], 0, 'useState adds a state value and setter to a function component.'),
            question('What should a component do when its props change?', ['Render from the new props', 'Mutate the props object', 'Write props into local storage automatically', 'Ignore every subsequent render'], 0, 'React components receive new props and render based on the updated values.'),
            question('Why should state updates based on the previous state use an updater function?', ['It receives the latest queued state value', 'It prevents the component from rendering', 'It mutates state in place', 'It runs only during server rendering'], 0, 'Updater functions avoid stale values when updates are queued.'),
          ),
        ],
      ),
      topic('AI & Machine Learning', 'ai-machine-learning',
        question('In supervised learning, training examples include:', ['Known target labels', 'Only random noise', 'No input features', 'A required human answer at prediction time'], 0, 'Supervised models learn from examples paired with target labels.'),
        question('A model that performs very well on training data but poorly on new data is likely:', ['Overfit', 'Underfit by definition', 'Untrained', 'Unsupervised'], 0, 'Overfitting is strong training performance that does not generalize.'),
        question('Data leakage happens when:', ['Training uses information unavailable at prediction time', 'A dataset has fewer than a million rows', 'Features are stored in columns', 'A model has two parameters'], 0, 'Leakage lets information from outside the valid training boundary inflate evaluation.'),
        [legacy('Data Science', 'data-science', 'chart-no-axes-combined',
          question('Which measure is the middle value of an ordered dataset?', ['Median', 'Mean', 'Range', 'Variance'], 0, 'The median is the central value after sorting the observations.'),
          question('What does a test set estimate in machine learning?', ['Performance on unseen data', 'Training speed only', 'The number of model parameters', 'The best feature names'], 0, 'A held-out test set estimates how a model performs on unseen examples.'),
          question('What is data leakage in model evaluation?', ['Using information unavailable at prediction time', 'Normalizing numeric columns', 'Splitting data into batches', 'Measuring a model twice'], 0, 'Leakage lets unavailable information inflate measured performance.'),
        )],
      ),
      topic('Databases', 'databases',
        question('What does a primary key identify?', ['A row uniquely within a table', 'A database server location', 'A backup schedule', 'A column display color'], 0, 'A primary key uniquely identifies each table row.'),
        question('What is a common benefit of a database index?', ['Faster reads for indexed queries', 'Smaller values in every row', 'Automatic elimination of all locks', 'Faster writes in every workload'], 0, 'Indexes speed up lookups but require storage and maintenance on writes.'),
        question('In ACID transactions, atomicity means:', ['All transaction changes happen or none do', 'Data is always duplicated', 'Every query is parallel', 'Rows are never updated'], 0, 'Atomicity makes a transaction an all-or-nothing unit.'),
        [
          topic('MongoDB', 'mongodb',
            question('MongoDB stores records primarily as which format?', ['BSON documents', 'CSV rows only', 'HTML nodes', 'Binary trees'], 0, 'MongoDB stores BSON documents in collections.'),
            question('Which MongoDB operation adds a document to a collection?', ['insertOne', 'findOne', 'aggregateOnly', 'dropIndex'], 0, 'insertOne inserts a single document into a collection.'),
            question('Which MongoDB feature supports multi-document ACID transactions?', ['Replica-set or sharded-cluster transactions', 'A TTL index by itself', 'A capped collection only', 'The shell prompt'], 0, 'MongoDB supports multi-document transactions on replica sets and sharded clusters.'),
          ),
          topic('SQL', 'sql',
            question('Which SQL command reads rows from a table?', ['SELECT', 'ALTER', 'DROP', 'GRANT'], 0, 'SELECT retrieves data from one or more tables.'),
            question('Which clause filters rows before grouping?', ['WHERE', 'HAVING', 'ORDER BY', 'LIMIT'], 0, 'WHERE filters source rows before grouping and aggregation.'),
            question('What does a LEFT JOIN preserve from its left input?', ['All left-side rows, with matching right-side values when available', 'Only rows that match on both sides', 'All right-side rows only', 'Only rows with null keys'], 0, 'A LEFT JOIN keeps every left row and fills unmatched right columns with nulls.'),
          ),
        ],
      ),
      topic('Cybersecurity', 'cybersecurity',
        question('What does multi-factor authentication require?', ['More than one type of proof of identity', 'Two copies of the same password', 'A longer username', 'A public profile'], 0, 'MFA combines different factor types such as knowledge and possession.'),
        question('A message that tricks someone into revealing a password is an example of:', ['Phishing', 'Load balancing', 'Version control', 'Tokenization'], 0, 'Phishing uses deceptive messages to steal information or trigger unsafe actions.'),
        question('Why add a unique salt before hashing each password?', ['To make precomputed hash attacks less reusable', 'To make the password reversible', 'To send the password to the browser', 'To guarantee the hash is short'], 0, 'Unique salts prevent identical passwords from producing identical stored hashes and frustrate rainbow tables.'),
      ),
      topic('Cloud Computing', 'cloud-computing',
        question('Which cloud service is commonly used to store files as objects?', ['Object storage', 'DNS hosting', 'A message queue', 'A relational view'], 0, 'Object storage stores data objects with metadata in scalable buckets or containers.'),
        question('Autoscaling primarily adjusts capacity in response to:', ['Workload demand', 'The developer’s keyboard layout', 'The number of source files', 'A fixed calendar date only'], 0, 'Autoscaling adds or removes resources as measured demand changes.'),
        question('Why deploy a critical service across multiple availability zones?', ['To reduce the impact of a single-zone failure', 'To remove the need for backups', 'To guarantee zero latency', 'To make all data public'], 0, 'Separate zones reduce correlated infrastructure failure risk within a region.'),
      ),
    ],
  },
  {
    name: 'Mathematics', slug: 'mathematics', description: 'Build confidence with numbers, patterns, space, and change.', icon: 'chart-no-axes-combined', color: '#b78539', children: [
      topic('Arithmetic', 'arithmetic',
        question('What is 18 + 27?', ['35', '45', '55', '46'], 1, 'Adding tens and ones gives 18 + 27 = 45.'),
        question('What is 3/4 of 64?', ['16', '32', '48', '56'], 2, 'One quarter of 64 is 16, and three quarters is 48.'),
        question('A price of $80 is discounted by 15%. What is the sale price?', ['$12', '$65', '$68', '$72'], 2, 'Fifteen percent of $80 is $12, so the sale price is $68.'),
      ),
      topic('Algebra', 'algebra',
        question('Solve x + 7 = 12.', ['3', '4', '5', '19'], 2, 'Subtract 7 from both sides to get x = 5.'),
        question('If 3x - 4 = 11, what is x?', ['3', '5', '7', '15'], 1, 'Add 4 to get 3x = 15, then divide by 3.'),
        question('What are the roots of x^2 - 5x + 6 = 0?', ['1 and 6', '-2 and -3', '2 and 3', '-1 and -6'], 2, 'The quadratic factors as (x - 2)(x - 3).'),
      ),
      topic('Geometry', 'geometry',
        question('How many sides does a hexagon have?', ['5', '6', '7', '8'], 1, 'A hexagon has six sides.'),
        question('What is the area of a triangle with base 10 cm and height 6 cm?', ['16 cm2', '30 cm2', '60 cm2', '120 cm2'], 1, 'Triangle area is one half times base times height: 30 cm2.'),
        question('A circle has radius 5. What is its circumference?', ['5 pi', '10 pi', '20 pi', '25 pi'], 1, 'Circumference equals 2 pi r, so it is 10 pi.'),
      ),
      topic('Probability', 'probability',
        question('What is the probability of getting heads on a fair coin toss?', ['0', '1/4', '1/2', '1'], 2, 'A fair coin has two equally likely outcomes.'),
        question('A bag has 3 red and 2 blue counters. What is the probability of drawing red?', ['2/5', '3/5', '1/2', '3/2'], 1, 'There are 3 favorable outcomes among 5 counters.'),
        question('Two fair dice are rolled. What is the probability their sum is 7?', ['1/12', '1/6', '1/4', '7/36'], 1, 'Six of the 36 equally likely ordered rolls sum to 7.'),
      ),
      topic('Statistics', 'statistics',
        question('Which measure is the middle value in an ordered list?', ['Mean', 'Median', 'Range', 'Mode'], 1, 'The median is the central value after sorting.'),
        question('What is the mean of 4, 6, 8, and 10?', ['6', '7', '8', '28'], 1, 'The sum is 28 and dividing by 4 gives 7.'),
        question('A large standard deviation usually indicates that data values are:', ['More spread out from the mean', 'All equal to the mean', 'Always negatively skewed', 'Categorical only'], 0, 'Standard deviation measures spread around the mean.'),
      ),
      topic('Calculus', 'calculus',
        question('What is the derivative of x^2?', ['x', '2x', '2', 'x^3'], 1, 'The power rule gives d(x^2)/dx = 2x.'),
        question('What does a definite integral commonly represent geometrically?', ['Signed area under a curve', 'The curve’s y-intercept only', 'The largest x-value', 'A derivative at one point'], 0, 'A definite integral accumulates signed area over an interval.'),
        question('What is the derivative of sin(x)?', ['-sin(x)', 'cos(x)', '-cos(x)', 'tan(x)'], 1, 'The derivative of sine is cosine.'),
      ),
    ],
  },
  {
    name: 'History', slug: 'history', description: 'Connect people, places, and events across time.', icon: 'book', color: '#bc704d', children: [
      topic('Ancient History', 'ancient-history',
        question('Which ancient civilization built the pyramids at Giza?', ['Ancient Egyptians', 'Phoenicians', 'Minoans', 'Hittites'], 0, 'The Giza pyramids were built in ancient Egypt during the Old Kingdom.'),
        question('The Code of Hammurabi is associated with which civilization?', ['Babylonian', 'Mayan', 'Roman', 'Inca'], 0, 'Hammurabi ruled the Babylonian Empire in the 18th century BCE.'),
        question('Which feature most distinguished the Athenian democracy of the 5th century BCE?', ['Eligible citizens voted directly in assemblies', 'Every resident held equal office', 'The ruler inherited absolute power', 'Women and enslaved people voted'], 0, 'Eligible male citizens participated directly, though most residents were excluded.'),
      ),
      topic('Medieval History', 'medieval-history',
        question('What was a common fortified residence of a medieval lord?', ['Castle', 'Amphitheatre', 'Ziggurat', ' observatory'], 0, 'Castles served as fortified residences and centers of local power.'),
        question('The Magna Carta was sealed in England in which year?', ['1066', '1215', '1492', '1660'], 1, 'King John sealed Magna Carta in 1215.'),
        question('Which institution was central to scholarly life in many medieval European towns?', ['The university', 'The factory', 'The stock exchange', 'The railway station'], 0, 'Medieval universities developed as centers for advanced study.'),
      ),
      topic('Modern History', 'modern-history',
        question('In which country did the Industrial Revolution begin?', ['Britain', 'Japan', 'Brazil', 'Egypt'], 0, 'Industrialization began in Britain in the 18th century.'),
        question('The French Revolution began in which year?', ['1688', '1776', '1789', '1848'], 2, 'The French Revolution began in 1789.'),
        question('Which idea was central to the 19th-century movement for Italian unification?', ['A single unified Italian nation-state', 'Restoration of the Western Roman Empire', 'A return to city-state rule', 'A French colony in Sicily'], 0, 'Risorgimento movements sought to unify the Italian states.'),
      ),
      topic('World History', 'world-history',
        question('The Silk Road connected East Asia most directly with:', ['The Mediterranean world', 'The Caribbean', 'Southern Africa', 'The Pacific islands only'], 0, 'Silk Road routes linked China and Central Asia with western trade networks.'),
        question('Which empire built an extensive road network across South America?', ['Inca Empire', 'Mughal Empire', 'Mali Empire', 'Byzantine Empire'], 0, 'Inca roads linked regions across the Andes.'),
        question('The 1884-85 Berlin Conference is chiefly associated with:', ['European partition of Africa', 'The end of the Cold War', 'The founding of the United Nations', 'The unification of Germany'], 0, 'European powers formalized rules for colonial claims in Africa at the conference.'),
      ),
      topic('Indian History', 'indian-history',
        question('Which ancient Indian city is associated with the Indus Valley Civilization?', ['Mohenjo-daro', 'Pataliputra', 'Madurai', 'Hampi'], 0, 'Mohenjo-daro was a major urban center of the Indus Valley Civilization.'),
        question('Who founded the Mughal Empire in India?', ['Babur', 'Akbar', 'Sher Shah Suri', 'Ashoka'], 0, 'Babur founded the Mughal Empire after the First Battle of Panipat in 1526.'),
        question('The Dandi March of 1930 protested which colonial policy?', ['The British salt tax and monopoly', 'The partition of Bengal', 'The Rowlatt Act', 'The Vernacular Press Act'], 0, 'Gandhi led the march to challenge British control and taxation of salt.'),
      ),
      topic('World Wars', 'world-wars',
        question('Which event is commonly cited as the immediate trigger of World War I?', ['Assassination of Archduke Franz Ferdinand', 'Fall of the Berlin Wall', 'Boston Tea Party', 'Sinking of the Lusitania'], 0, 'The assassination in Sarajevo triggered the July Crisis of 1914.'),
        question('D-Day, the Allied landing in Normandy, took place in:', ['1940', '1942', '1944', '1946'], 2, 'The Normandy landings began on 6 June 1944.'),
        question('The 1918 armistice ending fighting on the Western Front was signed on:', ['11 November', '1 September', '7 December', '8 May'], 0, 'The armistice took effect on 11 November 1918.'),
      ),
    ],
  },
  {
    name: 'Geography', slug: 'geography', description: 'Explore the places, landscapes, and patterns of our planet.', icon: 'globe-2', color: '#4d8c78', children: [
      topic('Countries & Capitals', 'countries-capitals',
        question('What is the capital of Japan?', ['Kyoto', 'Tokyo', 'Osaka', 'Sapporo'], 1, 'Tokyo is Japan’s capital.'),
        question('What is the capital of Australia?', ['Sydney', 'Melbourne', 'Canberra', 'Perth'], 2, 'Canberra is the national capital of Australia.'),
        question('Which capital city lies on the River Danube?', ['Lisbon', 'Budapest', 'Reykjavik', 'Dublin'], 1, 'Budapest is divided by the Danube River.'),
      ),
      topic('World Geography', 'world-geography',
        question('Which is the largest ocean?', ['Atlantic', 'Indian', 'Pacific', 'Arctic'], 2, 'The Pacific is the largest ocean by area.'),
        question('The Sahara Desert is primarily located on which continent?', ['Asia', 'Africa', 'Australia', 'South America'], 1, 'The Sahara spans much of northern Africa.'),
        question('Which strait separates Spain from Morocco?', ['Bering Strait', 'Strait of Gibraltar', 'Bosporus', 'Strait of Malacca'], 1, 'The Strait of Gibraltar separates Europe and Africa at their closest point.'),
      ),
      topic('Indian Geography', 'indian-geography',
        question('Which is the largest Indian state by area?', ['Rajasthan', 'Uttar Pradesh', 'Maharashtra', 'Gujarat'], 0, 'Rajasthan is India’s largest state by area.'),
        question('The Western Ghats run roughly parallel to which coast?', ['Eastern coast', 'Western coast', 'Northern border', 'Coromandel coast only'], 1, 'The Western Ghats parallel much of India’s western coastline.'),
        question('Which Indian river flows west into the Arabian Sea through a rift valley?', ['Godavari', 'Narmada', 'Mahanadi', 'Ganga'], 1, 'The Narmada flows west through a rift valley to the Arabian Sea.'),
      ),
      topic('Mountains & Rivers', 'mountains-rivers',
        question('Mount Everest is part of which mountain range?', ['Andes', 'Alps', 'Himalayas', 'Rockies'], 2, 'Mount Everest lies in the Himalayas.'),
        question('Which river flows through Egypt and drains into the Mediterranean Sea?', ['Nile', 'Congo', 'Zambezi', 'Niger'], 0, 'The Nile flows north through Egypt to the Mediterranean.'),
        question('Which river has the largest discharge volume into the ocean?', ['Amazon', 'Danube', 'Rhine', 'Colorado'], 0, 'The Amazon has the greatest average discharge of any river.'),
      ),
      topic('Maps & Locations', 'maps-locations',
        question('On most maps, which direction is at the top?', ['North', 'South', 'East', 'West'], 0, 'Most conventional maps place north at the top.'),
        question('Lines of longitude are used to measure distance east or west of the:', ['Equator', 'Prime Meridian', 'Tropic of Cancer', 'International Date Line only'], 1, 'Longitude measures angular position east or west of the Prime Meridian.'),
        question('A map scale of 1:50,000 means 1 cm on the map represents:', ['50 m on the ground', '500 m on the ground', '5 km on the ground', '50 km on the ground'], 1, 'At 1:50,000, one map centimeter represents 50,000 cm, or 500 m.'),
      ),
    ],
  },
  {
    name: 'English', slug: 'english', description: 'Strengthen language skills through words, texts, and ideas.', icon: 'book', color: '#9b6f8e', children: [
      topic('Grammar', 'grammar',
        question('Which word is the verb in “Birds fly south”?', ['Birds', 'fly', 'south', 'the'], 1, 'Fly expresses the action in the sentence.'),
        question('Choose the grammatically correct sentence.', ['She has lived here for five years.', 'She have lived here for five years.', 'She living here for five years.', 'She did lived here for five years.'], 0, 'The present perfect uses has with the singular subject she.'),
        question('In “The book that I borrowed is missing,” the clause “that I borrowed” is:', ['A relative clause modifying book', 'An independent clause', 'A coordinating conjunction', 'A predicate adjective'], 0, 'The relative clause identifies which book is meant.'),
      ),
      topic('Vocabulary', 'vocabulary',
        question('What does “brief” most nearly mean?', ['Short', 'Loud', 'Difficult', 'Ancient'], 0, 'Brief means lasting only a short time or using few words.'),
        question('What does “reluctant” mean?', ['Unwilling or hesitant', 'Eager and certain', 'Very noisy', 'Recently discovered'], 0, 'Reluctant describes hesitation or unwillingness.'),
        question('In “The evidence was compelling,” compelling most nearly means:', ['Convincing', 'Incomplete', 'Unrelated', 'Ordinary'], 0, 'Compelling evidence is persuasive and convincing.'),
      ),
      topic('Synonyms & Antonyms', 'synonyms-antonyms',
        question('Which word is a synonym for “begin”?', ['Commence', 'Finish', 'Forget', 'Delay'], 0, 'Commence means to begin.'),
        question('Which word is an antonym of “scarce”?', ['Rare', 'Limited', 'Abundant', 'Insufficient'], 2, 'Abundant means plentiful, the opposite of scarce.'),
        question('Which word is closest in meaning to “meticulous”?', ['Careful', 'Careless', 'Impatient', 'Uncertain'], 0, 'Meticulous means showing great attention to detail.'),
      ),
      topic('Literature', 'literature',
        question('Who wrote “Pride and Prejudice”?', ['Jane Austen', 'Mary Shelley', 'George Eliot', 'Virginia Woolf'], 0, 'Jane Austen published Pride and Prejudice in 1813.'),
        question('A story told by a narrator using “I” is written in which point of view?', ['First person', 'Second person', 'Third-person omniscient', 'Objective third person'], 0, 'First-person narrators refer to themselves as “I” or “we”.'),
        question('A recurring image or idea that develops a literary work is commonly called a:', ['Motif', 'Footnote', 'Meter', 'Stage direction'], 0, 'A motif is a recurring element that contributes to a work’s themes.'),
      ),
      topic('Reading Comprehension', 'reading-comprehension',
        question('What is the main idea of a passage?', ['Its central point', 'The longest sentence', 'A detail from the final line', 'The author’s biography'], 0, 'The main idea summarizes what the passage is chiefly about.'),
        question('If a passage says a character “gripped the umbrella as the wind howled,” what is most reasonable to infer?', ['The weather is windy', 'The character is indoors', 'The umbrella is broken', 'It is certainly snowing'], 0, 'The wording supports an inference of windy conditions, but not snow or damage.'),
        question('Which detail best supports a claim that a town reduced traffic pollution?', ['Measured roadside nitrogen dioxide fell after bus service expanded', 'The town planted flowers in a park', 'Residents prefer sunny days', 'A nearby shop changed its sign'], 0, 'A measured pollutant change tied to the transport change directly supports the claim.'),
      ),
    ],
  },
  {
    name: 'Sports', slug: 'sports', description: 'Test your knowledge of the games, athletes, and records you love.', icon: 'trophy', color: '#4b8b5c', children: [
      topic('Cricket', 'cricket',
        question('How many legal deliveries are in a standard over?', ['4', '5', '6', '8'], 2, 'A standard over contains six legal deliveries.'),
        question('What is a batter’s score of 100 runs in an innings called?', ['A century', 'A maiden', 'A hat-trick', 'A follow-on'], 0, 'A century is an individual score of at least 100 runs.'),
        question('In Test cricket, what is a follow-on?', ['An option for the side batting second after a large first-innings deficit', 'A compulsory change of ball every over', 'A penalty for a no-ball', 'A batter’s decision to retire'], 0, 'The follow-on allows the leading side to make the opponent bat again immediately, subject to the margin and rules.'),
      ),
      topic('Football', 'football',
        question('How many players from one team start on the field in association football?', ['9', '10', '11', '12'], 2, 'Each team begins with eleven players, including the goalkeeper.'),
        question('What is awarded when a defending player commits a direct-free-kick foul in their own penalty area?', ['Corner kick', 'Penalty kick', 'Throw-in', 'Goal kick'], 1, 'A direct-free-kick offence in the defender’s penalty area results in a penalty kick.'),
        question('How far is the penalty mark from the goal line in association football?', ['9.15 m', '10 m', '11 m', '12 m'], 2, 'The penalty mark is 11 metres from the midpoint between the goalposts.'),
      ),
      topic('Basketball', 'basketball',
        question('How many points is a successful free throw worth?', ['1', '2', '3', '4'], 0, 'A free throw is worth one point.'),
        question('How long is the NBA shot clock?', ['14 seconds', '24 seconds', '30 seconds', '35 seconds'], 1, 'The NBA shot clock is 24 seconds, with specific reset rules.'),
        question('What is the result of a defensive player committing six personal fouls in an NBA game?', ['The player fouls out', 'The team loses one point', 'The game ends immediately', 'The player switches teams'], 0, 'NBA players are disqualified after six personal fouls.'),
      ),
      topic('Tennis', 'tennis',
        question('What score comes after 30 in a standard tennis game?', ['35', '40', '45', 'Advantage'], 1, 'The standard sequence is love, 15, 30, 40, then game, subject to deuce.'),
        question('At deuce in a standard game, a player generally needs:', ['One point to win', 'Two consecutive points to win', 'Three points to win', 'A successful serve only'], 1, 'A player must win advantage and then the next point.'),
        question('Which Grand Slam tournament is played on clay courts?', ['Wimbledon', 'US Open', 'French Open', 'Australian Open'], 2, 'The French Open is played on clay at Roland-Garros.'),
      ),
      topic('Olympics', 'olympics',
        question('How often are the Summer Olympic Games usually held?', ['Every 2 years', 'Every 4 years', 'Every 5 years', 'Every 6 years'], 1, 'The Summer Olympics are normally held every four years.'),
        question('The Olympic rings represent how many continents in the traditional symbolism?', ['3', '5', '6', '7'], 1, 'The five interlocking rings symbolize the union of the inhabited continents.'),
        question('Which city hosted the first modern Olympic Games in 1896?', ['Paris', 'Athens', 'London', 'Rome'], 1, 'Athens hosted the first modern Olympics in 1896.'),
      ),
      topic('Sports Records', 'sports-records',
        question('In a marathon, what is the official race distance?', ['40 km', '42.195 km', '45 km', '50 km'], 1, 'The marathon distance is 42.195 kilometres.'),
        question('A hat-trick in many team sports generally means a player has:', ['Scored three times in one game', 'Played three seasons', 'Made three substitutions', 'Won three coin tosses'], 0, 'A hat-trick commonly means three scoring achievements by one player in a match.'),
        question('Which athletics event combines ten track-and-field disciplines?', ['Decathlon', 'Heptathlon', 'Pentathlon', 'Triathlon'], 0, 'The decathlon consists of ten events.'),
      ),
    ],
  },
  {
    name: 'Entertainment', slug: 'entertainment', description: 'Play along with stories, screens, music, and games.', icon: 'sparkles', color: '#9a6f9b', children: [
      topic('Movies', 'movies',
        question('What does a film director primarily guide?', ['The creative and dramatic realization of a film', 'The cinema ticket price', 'The audience seating plan', 'The projector bulb only'], 0, 'The director leads the film’s artistic and dramatic execution.'),
        question('Which award is presented by the Academy of Motion Picture Arts and Sciences?', ['Oscar', 'Grammy', 'Tony', 'Booker Prize'], 0, 'The Academy Awards are commonly called the Oscars.'),
        question('In filmmaking, a “long take” is a shot that:', ['Continues for an extended duration without a cut', 'Uses only a long lens', 'Shows the entire film in one frame', 'Contains no dialogue'], 0, 'A long take maintains a shot for an extended time before editing.'),
      ),
      topic('Anime', 'anime',
        question('Anime is animation most strongly associated with which country?', ['Japan', 'Canada', 'Spain', 'Brazil'], 0, 'Anime is a broad term for animation associated with Japan.'),
        question('In anime production, a storyboard mainly helps plan:', ['The sequence and composition of scenes', 'The soundtrack royalties', 'The audience age rating only', 'The final streaming bitrate'], 0, 'Storyboards map shots and action before full animation.'),
        question('What does “manga” generally refer to?', ['Japanese comics and graphic novels', 'A type of animation camera', 'A film editing technique', 'A musical scale'], 0, 'Manga refers to Japanese comics and graphic novels.'),
      ),
      topic('TV Shows', 'tv-shows',
        question('What is a pilot episode?', ['An initial episode made to introduce or sell a series', 'The final episode of every series', 'A recap without new scenes', 'A show broadcast only on aircraft'], 0, 'A pilot introduces a series concept and is often used to evaluate it.'),
        question('A season finale is usually:', ['The closing episode of a season', 'The first episode of a season', 'A series title card', 'A commercial break'], 0, 'A season finale closes a season’s episode run.'),
        question('A show released with every episode available at once is commonly described as:', ['Binge-released', 'Serialized live only', 'Syndicated daily', 'A theatrical short'], 0, 'A binge release makes a full season or batch available together.'),
      ),
      topic('Music', 'music',
        question('How many notes are in a standard major scale?', ['5', '7', '8', '12'], 1, 'A major scale has seven distinct scale degrees before the octave.'),
        question('What does tempo describe in music?', ['The speed of the beat', 'The loudness of one note', 'The instrument’s material', 'The number of performers'], 0, 'Tempo is the pace of the underlying beat.'),
        question('In equal temperament, how many semitones make an octave?', ['8', '10', '12', '14'], 2, 'A standard octave spans twelve semitones.'),
      ),
      topic('Gaming', 'gaming',
        question('What does “NPC” commonly stand for in a video game?', ['Non-player character', 'New playable console', 'Network process code', 'Next-person challenge'], 0, 'An NPC is a character not controlled directly by a player.'),
        question('In a multiplayer game, latency most directly refers to:', ['Delay between an action and its network response', 'The game’s file size', 'The number of available maps', 'The screen’s color depth'], 0, 'Latency is the time delay in communication between systems.'),
        question('A game’s frame rate is measured in:', ['Frames per second', 'Pixels per inch', 'Bytes per frame', 'Hertz per player'], 0, 'Frame rate is the number of frames rendered each second.'),
      ),
    ],
  },
  {
    name: 'General Knowledge', slug: 'general-knowledge', description: 'A wide-ranging mix of facts about our shared world.', icon: 'globe-2', color: '#c1963d', children: [
      topic('Current Affairs', 'current-affairs',
        question('Which organization publishes the annual Human Development Report?', ['UN Development Programme', 'World Trade Organization', 'International Olympic Committee', 'International Union for Conservation of Nature'], 0, 'The UN Development Programme publishes the Human Development Report.'),
        question('The Paris Agreement is an international agreement focused on:', ['Climate change', 'Nuclear disarmament only', 'Ocean shipping tariffs', 'World heritage sites'], 0, 'The Paris Agreement sets a framework for addressing climate change.'),
        question('Which institution sets monetary policy for the euro area?', ['European Central Bank', 'European Parliament', 'European Court of Auditors', 'Council of Europe'], 0, 'The European Central Bank is responsible for monetary policy in the euro area.'),
      ),
      topic('Inventions', 'inventions',
        question('Who is widely credited with developing the practical incandescent light bulb?', ['Thomas Edison', 'Louis Pasteur', 'Johannes Gutenberg', 'Alexander Fleming'], 0, 'Edison and his team developed a commercially practical incandescent lamp.'),
        question('The movable-type printing press associated with Johannes Gutenberg developed in:', ['15th-century Europe', '9th-century Australia', '18th-century South America', '20th-century Africa'], 0, 'Gutenberg’s press transformed printing in 15th-century Europe.'),
        question('Who is commonly credited with inventing the World Wide Web?', ['Tim Berners-Lee', 'Vint Cerf', 'Grace Hopper', 'Claude Shannon'], 0, 'Tim Berners-Lee proposed and implemented the World Wide Web at CERN.'),
      ),
      topic('Famous People', 'famous-people',
        question('Who wrote the play “Hamlet”?', ['William Shakespeare', 'Charles Dickens', 'Oscar Wilde', 'Geoffrey Chaucer'], 0, 'Hamlet is a tragedy by William Shakespeare.'),
        question('Who became the first woman to win a Nobel Prize?', ['Marie Curie', 'Ada Lovelace', 'Rosalind Franklin', 'Lise Meitner'], 0, 'Marie Curie received the 1903 Nobel Prize in Physics.'),
        question('Which Indian mathematician is known for major contributions to number theory and infinite series?', ['Srinivasa Ramanujan', 'C. V. Raman', 'Homi Bhabha', 'Satyendra Nath Bose'], 0, 'Ramanujan made influential contributions to number theory and series.'),
      ),
      topic('Organizations', 'organizations',
        question('Where is the headquarters of the United Nations located?', ['New York City', 'Geneva', 'Paris', 'Vienna'], 0, 'The UN headquarters is in New York City.'),
        question('Which organization coordinates international public health work?', ['World Health Organization', 'World Customs Organization', 'International Maritime Organization', 'World Meteorological Organization'], 0, 'The World Health Organization is the UN agency for international public health.'),
        question('Which institution is the principal judicial organ of the United Nations?', ['International Court of Justice', 'International Criminal Court', 'Permanent Court of Arbitration', 'European Court of Human Rights'], 0, 'The International Court of Justice is the UN’s principal judicial organ.'),
      ),
      topic('World Records', 'world-records',
        question('Which reference work is known for documenting record-breaking achievements worldwide?', ['Guinness World Records', 'Oxford Dictionary of Quotations', 'World Atlas', 'The Nobel Register'], 0, 'Guinness World Records documents notable record achievements.'),
        question('What should a fair record attempt generally provide?', ['Clear rules and verifiable evidence', 'Only a personal estimate', 'An anonymous claim with no witnesses', 'A result that cannot be repeated or checked'], 0, 'Clear criteria and evidence make a record claim verifiable.'),
        question('Why do record organizations update records over time?', ['New verified achievements can surpass previous marks', 'Every record expires each week', 'Old results are always incorrect', 'Measurements are no longer needed'], 0, 'Records can change when a new achievement is verified under the rules.'),
      ),
    ],
  },
  {
    name: 'Business', slug: 'business', description: 'Learn how organizations create, manage, and exchange value.', icon: 'chart-no-axes-combined', color: '#607b59', children: [
      topic('Economics', 'economics',
        question('What is inflation?', ['A general rise in prices over time', 'A fall in all wages', 'A measure of population size', 'A government budget surplus'], 0, 'Inflation is a sustained increase in the general price level.'),
        question('If demand rises while supply stays constant, what commonly happens to the market price?', ['It rises', 'It falls', 'It must become zero', 'It cannot change'], 0, 'Higher demand with unchanged supply tends to put upward pressure on price.'),
        question('The opportunity cost of a choice is:', ['The value of the best alternative given up', 'The total money in a bank', 'A fee charged by every market', 'The profit after tax'], 0, 'Opportunity cost measures the next-best alternative forgone.'),
      ),
      topic('Finance', 'finance',
        question('What is the principal of a loan?', ['The original amount borrowed', 'The interest rate only', 'The repayment date', 'A bank’s annual profit'], 0, 'Principal is the original amount of money borrowed or invested.'),
        question('What does diversification aim to do in an investment portfolio?', ['Spread exposure across different assets', 'Guarantee a profit', 'Eliminate every market risk', 'Concentrate funds in one company'], 0, 'Diversification can reduce concentration risk but cannot eliminate all risk.'),
        question('With compound interest, interest is calculated on:', ['Principal and previously accumulated interest', 'Principal only forever', 'Fees but never principal', 'The inflation rate only'], 0, 'Compound interest earns interest on accumulated interest as well as principal.'),
      ),
      topic('Marketing', 'marketing',
        question('What is a target market?', ['The specific group a product is intended to serve', 'Every person in a country', 'A company’s accounting ledger', 'A list of production machines'], 0, 'A target market is the audience a business aims to reach.'),
        question('In the traditional marketing mix, the “4 Ps” include product, price, place, and:', ['Promotion', 'Profit', 'People', 'Planning'], 0, 'The traditional 4 Ps are product, price, place, and promotion.'),
        question('A/B testing compares two versions primarily to:', ['Measure which performs better against a defined outcome', 'Make both versions identical', 'Replace customer research with guesses', 'Guarantee a higher price'], 0, 'A/B tests compare variants using measured outcomes.'),
      ),
      topic('Entrepreneurship', 'entrepreneurship',
        question('What is a business plan commonly used to communicate?', ['A venture’s goals and how it intends to reach them', 'A guarantee of future profit', 'A customer’s personal password', 'A list of unrelated inventions'], 0, 'A business plan outlines goals, market, operations, and financial assumptions.'),
        question('A minimum viable product is best described as:', ['A simple version used to test key assumptions with users', 'A fully finished product with every planned feature', 'A product with no intended users', 'A company’s annual tax return'], 0, 'An MVP tests a core value proposition with the least useful product scope.'),
        question('Product-market fit broadly means that:', ['A product meets a strong need for a defined market', 'A company has the largest office', 'A product has no competitors', 'Every customer pays the same amount'], 0, 'Product-market fit describes meaningful demand from a target market.'),
      ),
      topic('Management', 'management',
        question('What is a primary purpose of setting team goals?', ['Aligning work around clear outcomes', 'Removing the need to communicate', 'Guaranteeing every task takes equal time', 'Avoiding feedback'], 0, 'Clear goals help coordinate priorities and measure progress.'),
        question('Delegation means:', ['Assigning responsibility and appropriate authority to others', 'Avoiding all decisions', 'Transferring ownership of a company', 'Removing a project deadline'], 0, 'Delegation entrusts work and decision scope to another team member.'),
        question('A useful performance indicator should be:', ['Relevant to an outcome and consistently measurable', 'Chosen only because it is easy to count', 'Changed every day without explanation', 'Unrelated to the team’s goals'], 0, 'A meaningful KPI is measurable and connected to the outcome being managed.'),
      ),
    ],
  },
]

export const legacyCategoryParents = {
  javascript: 'programming',
  python: 'programming',
  react: 'web-development',
  html: 'web-development',
  css: 'web-development',
  'data-science': 'ai-machine-learning',
}

export function flattenSubjectCategories(groups = subjectGroups) {
  const rows = []
  const visit = (nodes, parentSlug = null, rootSlug = null) => {
    for (const node of nodes) {
      const { children = [], questions, legacy: isLegacy, ...category } = node
      rows.push({ ...category, parentSlug, rootSlug: rootSlug || node.slug, legacy: Boolean(isLegacy) })
      visit(children, node.slug, rootSlug || node.slug)
    }
  }
  visit(groups)
  return rows
}

export function flattenSubjectQuizzes(groups = subjectGroups) {
  const quizzes = []
  const visit = nodes => {
    for (const node of nodes) {
      if (node.questions?.length) {
        for (const item of node.questions) {
          quizzes.push({
            title: `${node.name}: ${item.difficulty} practice`,
            description: `A focused ${item.difficulty.toLowerCase()} ${node.name.toLowerCase()} quiz.`,
            category: node.slug,
            difficulty: item.difficulty,
            timeLimit: 3,
            featured: false,
            questions: [item],
          })
        }
      }
      visit(node.children || [])
    }
  }
  visit(groups)
  return quizzes
}
